Repository SeoulGreenJacket/Dr.Trash-BE, pull requests merged in 2022-08, with the labels that each got.

#6 도커 파일 작성
  .dockerignore
  Dockerfile
  entrypoint.sh
Labels: ✨ enhancement

#8 템플릿을 만들었어요
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  common/swagger-options.ts
  src/auth/auth.controller.ts
  src/auth/dto/user.dto.ts
  src/main.ts
Labels: ✨ enhancement

#14 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🧹 chore

#20 fix: Change common directory
  src/common/swagger-options.ts
  src/main.ts
Labels: 🐛 fix

#18 fix: Add a shebang line #13
  Dockerfile
  docker-entrypoint.sh
  entrypoint.sh
Labels: ✨ enhancement

#23 refactor: Change nest-pgpromise to pg #22
  package-lock.json
  package.json
  src/database/database.module.ts
  src/database/database.service.ts
Labels: 🛠 refactor

#28 sort-imports, no-multi-empty-lines 삭제
  .eslintrc.js
Labels: 🛠 refactor

#31 db 생성과 연결
  nest-cli.json
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/jwt-payload.dto.ts
  src/auth/dto/user-social.dto.ts
  src/auth/dto/user.dto.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/kakao.strategy.ts
  src/auth/strategy/refresh-jwt.strategy.ts
  src/database/database.module.ts
  src/database/database.service.ts
  src/users/dto/create-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
  test/app.e2e-spec.ts
Labels: 🛠 refactor

#34 Kakao
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/user-social.dto.ts
  src/auth/strategy/kakao.strategy.ts
  src/users/dto/create-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/users.repository.ts
Labels: ✨ enhancement

#35 Enhance 30 jwt token
  src/auth/auth.controller.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/auth/dto/jwt-payload.dto.ts
  src/auth/dto/jwt-token.dto.ts
  src/auth/guard/refresh-jwt-auth.guard.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/refresh-jwt.strategy.ts
Labels: ✨ enhancement

#38 Refactor 36 db
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/strategy/kakao.strategy.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: 🛠 refactor

#40 Fix 39 token method
  src/auth/auth.controller.ts
  src/auth/strategy/refresh-jwt.strategy.ts
Labels: 🐛 fix

#54 Fix type error #53
  src/cache/cache.service.ts
Labels: 🐛 fix

#57 Enhance 56 environments ts
  src/auth/auth.module.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/kakao.strategy.ts
  src/auth/strategy/refresh-jwt.strategy.ts
  src/cache/cache.module.ts
  src/cache/cache.service.ts
  src/common/environments.ts
  src/database/database.module.ts
  src/users/users.repository.ts
Labels: 🛠 refactor
