Repository SeoulGreenJacket/Dr.Trash-BE, pull requests merged in 2022-09, with the labels that each got.

#62 `trash` 엔드포인트
  src/app.module.ts
  src/auth/decorator/user-id.decorator.ts
  src/cache/cache.module.ts
  src/cache/cache.service.ts
  src/common/environments.ts
  src/trash/dto/trash-info.dto.ts
  src/trash/dto/trash-summary.dto.ts
  src/trash/entities/trash.entity.ts
  src/trash/trash.controller.ts
  src/trash/trash.module.ts
  src/trash/trash.repository.ts
  src/trash/trash.service.ts
  src/trashcans/dto/create-trashcan.dto.ts
  src/trashcans/dto/update-trashcan.dto.ts
  src/trashcans/entities/trashcan.entity.ts
  src/trashcans/pipe/trashcan-by-id.pipe.ts
  src/trashcans/trashcans.controller.ts
  src/trashcans/trashcans.module.ts
  src/trashcans/trashcans.repository.ts
  src/trashcans/trashcans.service.ts
Labels: ✨ enhancement

#52 enhance: User ID decorator #49
  src/auth/decorator/user-id.decorator.ts
Labels: ✨ enhancement

#61 Refactor 60 cache수정
  src/cache/cache.service.ts
Labels: 🛠 refactor

#58 Enhance 41 users
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/jwt-token-response.dto.ts
  src/auth/dto/jwt-token.dto.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/refresh-jwt.strategy.ts
  src/auth/types/jwt-token-payload.type.ts
  src/common/environments.ts
  src/common/swagger-options.ts
  src/main.ts
  src/users/dto/user-rank-response.dto.ts
  src/users/dto/user-response.dto.ts
  src/users/dto/user-update.dto.ts
  src/users/entities/achievement.entity.ts
  src/users/guard/check-user-id.guard.ts
  src/users/types/grade.enum.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: ✨ enhancement

#55 Trashcans endpoint
  src/trashcans/dto/create-trashcan.dto.ts
  src/trashcans/entities/trashcan.entity.ts
Labels: ✨ enhancement

#69 Fix 68 bug
  src/auth/strategy/kakao.strategy.ts
  src/users/users.controller.ts
Labels: 🐛 fix

#71 Refactor 70 user id deco
  src/auth/auth.controller.ts
  src/auth/strategy/kakao.strategy.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
Labels: 🛠 refactor

#74 dependency: 사용하지 않는 패키지 삭제
  package-lock.json
  package.json
Labels: 🧹 chore

#76 Enhancement 72 user deco
  src/auth/auth.controller.ts
  src/auth/decorator/access-user.decorator.ts
  src/auth/decorator/refresh-user.decorator.ts
  src/trash/trash.controller.ts
  src/trashcans/trashcans.controller.ts
  src/users/users.controller.ts
Labels: ✨ enhancement

#64 Enhance 43 achievements
  src/achievements/achievement.interceptor.ts
  src/achievements/achievements.controller.ts
  src/achievements/achievements.module.ts
  src/achievements/achievements.repository.ts
  src/achievements/achievements.service.ts
  src/achievements/entity/achievement.entity.ts
  src/achievements/entity/user-achievement.entity.ts
  src/app.module.ts
  src/cache/cache.module.ts
  src/cache/cache.service.ts
  src/common/environments.ts
Labels: ✨ enhancement

#86 countUserTrash 구현
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: ✨ enhancement
