Repository SeoulGreenJacket/Dr.Trash-BE, pull requests merged in 2022-11, with the labels that each got.

#112 Enhance article user
  src/articles/articles.repository.ts
  src/articles/dto/response-article-dto.ts
Labels: 🛠 refactor

#111 fix: 업적 아이디 수정
  src/achievements/achievements.service.ts
Labels: 🧹 chore

#116 fix: Add trashcan type
  src/trash/trash.controller.ts
  src/trash/trash.repository.ts
  src/trash/trash.service.ts
Labels: 🐛 fix

#118 Revert "fix: Add trashcan type"
  src/trash/trash.controller.ts
  src/trash/trash.repository.ts
  src/trash/trash.service.ts
Labels: 🐛 fix
